services:
  app:
    container_name: go_container
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 9090:9090
      - 9091:9091
    tty: true
    volumes:
      - ./api/:/api
      - .env:/api/.env

  db:
    container_name: go_db_container
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - go_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
        
volumes:
  go_db_volume:
  dgn_node_modules:

